# Generated by Django 2.2.7 on 2019-11-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='url',
            new_name='email_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='topic',
        ),
    ]
