# Generated by Django 2.2.7 on 2019-11-26 12:32

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20191125_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
