# Generated by Django 2.2.7 on 2019-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20191126_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to='Member_profile_upload/'),
        ),
    ]
