# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20191128_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='board_detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='board_member',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
