# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20191128_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_url',
            field=models.URLField(),
        ),
    ]
