# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20191128_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='board_detail',
            field=models.TextField(blank=True, max_length=220, null=True),
        ),
    ]
