# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_member_board_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='board_detail',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='board_member',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=264),
        ),
    ]
